[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
price_prediction_market = "A83FGFK76LfLQTESqJJ1B2FGTU86PbbbxCXS7ibAw7r3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../mykey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
